datasets = {
    "uci_adult": {
        "path": "UCI_adult/adult.csv",
        "sep": ",",
        "drop_cols": ["fnlwgt", "education"],
        "data_types": [
            ("age", "positive int"),
            ("workclass", "categorical"),
            ("education-num", "positive int"),
            ("marital-status", "categorical"),
            ("occupation", "categorical"),
            ("relationship", "categorical"),
            ("race", "categorical"),
            ("sex", "categorical binary"),
            ("capital-gain", "positive float"),
            ("capital-loss", "positive float"),
            ("hours-per-week", "positive int"),
            ("native-country", "categorical"),
            ("salary", "categorical binary"),
        ],
    },
    "kaggle_cardio": {
        "path": "kaggle_cardio_disease/cardio_train.csv",
        "sep": ";",
        "drop_cols": ["id"],
        "data_types": [
            ("age", "positive int"),
            ("gender", "categorical"),
            ("height", "positive int"),
            ("weight", "positive int"),
            ("ap_hi", "positive int"),
            ("ap_lo", "positive int"),
            ("cholesterol", "categorical"),
            ("gluc", "categorical"),
            ("smoke", "categorical"),
            ("alco", "categorical"),
            ("active", "categorical"),
            ("cardio", "categorical"),
        ],
    },
}
